#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 5424026
#
%define keepstatic 1
Name     : openjpeg
Version  : 2.5.3
Release  : 25
URL      : https://github.com/uclouvain/openjpeg/archive/v2.5.3/openjpeg-2.5.3.tar.gz
Source0  : https://github.com/uclouvain/openjpeg/archive/v2.5.3/openjpeg-2.5.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause MIT libpng-2.0
Requires: openjpeg-bin = %{version}-%{release}
Requires: openjpeg-lib = %{version}-%{release}
Requires: openjpeg-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : glibc-dev
BuildRequires : libpng-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : pkgconfig(lcms2)
BuildRequires : tiff-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
========================================================================
OpenJPIP software 2.1 ReadMe

%package bin
Summary: bin components for the openjpeg package.
Group: Binaries
Requires: openjpeg-license = %{version}-%{release}

%description bin
bin components for the openjpeg package.


%package dev
Summary: dev components for the openjpeg package.
Group: Development
Requires: openjpeg-lib = %{version}-%{release}
Requires: openjpeg-bin = %{version}-%{release}
Provides: openjpeg-devel = %{version}-%{release}
Requires: openjpeg = %{version}-%{release}

%description dev
dev components for the openjpeg package.


%package lib
Summary: lib components for the openjpeg package.
Group: Libraries
Requires: openjpeg-license = %{version}-%{release}

%description lib
lib components for the openjpeg package.


%package license
Summary: license components for the openjpeg package.
Group: Default

%description license
license components for the openjpeg package.


%package staticdev
Summary: staticdev components for the openjpeg package.
Group: Default
Requires: openjpeg-dev = %{version}-%{release}

%description staticdev
staticdev components for the openjpeg package.


%prep
%setup -q -n openjpeg-2.5.3
cd %{_builddir}/openjpeg-2.5.3
pushd ..
cp -a openjpeg-2.5.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1733819229
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1733819229
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openjpeg
cp %{_builddir}/openjpeg-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/openjpeg/a1a529b822da257f69972ea711df38489e9d4251 || :
cp %{_builddir}/openjpeg-%{version}/src/bin/wx/OPJViewer/source/license.txt %{buildroot}/usr/share/package-licenses/openjpeg/28399384e8bacfe952bb12c4c52a9ba009a9c18d || :
cp %{_builddir}/openjpeg-%{version}/thirdparty/astyle/LICENSE.md %{buildroot}/usr/share/package-licenses/openjpeg/3ad29cc31a206b0662eb91917964b82f11b3df16 || :
cp %{_builddir}/openjpeg-%{version}/thirdparty/liblcms2/COPYING %{buildroot}/usr/share/package-licenses/openjpeg/f595de201a37b00737678b96b4c4a10d5bc5f6d9 || :
cp %{_builddir}/openjpeg-%{version}/thirdparty/libpng/LICENSE %{buildroot}/usr/share/package-licenses/openjpeg/570f5344ea5facacb5e0bbb3fe4e0674189a5f0e || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
mkdir -p %{buildroot}/usr/lib64/
mkdir -p %{buildroot}-v3/usr/lib64/
#mv %{buildroot}/usr/lib/libopenjp2.so* %{buildroot}/usr/lib64/
#@mv %{buildroot}-v3/usr/lib/libopenjp2.so* %{buildroot}-v3/usr/lib64/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/opj_compress
/V3/usr/bin/opj_decompress
/V3/usr/bin/opj_dump
/usr/bin/opj_compress
/usr/bin/opj_decompress
/usr/bin/opj_dump

%files dev
%defattr(-,root,root,-)
/usr/include/openjpeg-2.5/openjpeg.h
/usr/include/openjpeg-2.5/opj_config.h
/usr/lib64/cmake/openjpeg-2.5/OpenJPEGConfig.cmake
/usr/lib64/cmake/openjpeg-2.5/OpenJPEGConfigVersion.cmake
/usr/lib64/cmake/openjpeg-2.5/OpenJPEGTargets-relwithdebinfo.cmake
/usr/lib64/cmake/openjpeg-2.5/OpenJPEGTargets.cmake
/usr/lib64/libopenjp2.so
/usr/lib64/pkgconfig/libopenjp2.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libopenjp2.so.2.5.3
/usr/lib64/libopenjp2.so.2.5.3
/usr/lib64/libopenjp2.so.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openjpeg/28399384e8bacfe952bb12c4c52a9ba009a9c18d
/usr/share/package-licenses/openjpeg/3ad29cc31a206b0662eb91917964b82f11b3df16
/usr/share/package-licenses/openjpeg/570f5344ea5facacb5e0bbb3fe4e0674189a5f0e
/usr/share/package-licenses/openjpeg/a1a529b822da257f69972ea711df38489e9d4251
/usr/share/package-licenses/openjpeg/f595de201a37b00737678b96b4c4a10d5bc5f6d9

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libopenjp2.a
